# Generated by Django 6.1.1 on 2026-09-28 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NurseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('handed_over', 'Handed Over')], default='active', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assigned_on'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=140)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=60)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('patient_type', models.CharField(choices=[('opd', 'OPD'), ('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('icu', 'ICU'), ('discharged', 'Discharged'), ('follow_up', 'Follow-up'), ('scheduled', 'Scheduled Appointment')], default='opd', max_length=20)),
                ('current_status', models.CharField(choices=[('registered', 'Registered'), ('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('admitted', 'Admitted'), ('under_treatment', 'Under Treatment'), ('stable', 'Stable'), ('critical', 'Critical'), ('ready_for_discharge', 'Ready for Discharge'), ('discharged', 'Discharged'), ('follow_up', 'Follow-up')], default='registered', max_length=30)),
                ('admission_status', models.CharField(choices=[('not_admitted', 'Not Admitted'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='not_admitted', max_length=20)),
                ('allergies', models.CharField(blank=True, help_text='Comma separated list of known allergies.', max_length=250)),
                ('medical_history', models.TextField(blank=True)),
                ('chronic_conditions', models.CharField(blank=True, max_length=250)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=120)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('bp_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
