# Generated by Django 6.1.1 on 2026-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
