# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_target', models.CharField(blank=True, help_text='Optional role code for broadcast messages.', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('appointment', 'Appointment'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('bed', 'Bed Management'), ('billing', 'Billing'), ('insurance', 'Insurance'), ('admission', 'Admission'), ('discharge', 'Discharge'), ('inventory', 'Inventory'), ('document', 'Documents'), ('ai', 'AI Assistant'), ('system', 'System')], default='system', max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
