# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('procedure', 'Procedure'), ('diagnostic', 'Diagnostic'), ('vaccination', 'Vaccination'), ('emergency', 'Emergency'), ('teleconsultation', 'Teleconsultation')], default='consultation', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('token_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
    ]
