"""
Default permission matrix for every role.

Modules are keyed by the API surface (``/api/<module>/``) and each entry lists
the allowed actions: ``view``, ``create``, ``edit``, ``delete``.
"""

from .models import RoleCode

ALL_ACTIONS = ["view", "create", "edit", "delete"]

MODULE_LABELS = {
    "users": "Users & Roles",
    "departments": "Departments",
    "doctors": "Doctors",
    "patients": "Patients",
    "vitals": "Patient Vitals",
    "appointments": "Appointments",
    "opd": "OPD Consultations",
    "emergency": "Emergency",
    "admissions": "Admissions",
    "beds": "Bed Management",
    "laboratory": "Laboratory",
    "radiology": "Radiology",
    "pharmacy": "Pharmacy",
    "prescriptions": "Prescriptions",
    "surgery": "Operation Theatre",
    "bloodbank": "Blood Bank",
    "documents": "Medical Documents",
    "ai": "AI Assistants",
    "billing": "Billing",
    "insurance": "Insurance",
    "inventory": "Inventory",
    "staff": "Staff & Shifts",
    "notifications": "Notifications",
    "analytics": "Analytics",
    "audit": "Audit Logs",
    "hospital": "Hospital Settings",
    "navigation": "Hospital Navigation",
    "portal": "Patient Portal",
}

_ALL_MODULES = {module: list(ALL_ACTIONS) for module in MODULE_LABELS}


DEFAULT_ROLE_PERMISSIONS = {
    RoleCode.SUPER_ADMIN: dict(_ALL_MODULES),
    RoleCode.HOSPITAL_ADMIN: dict(_ALL_MODULES),
    RoleCode.HOD: {
        "users": ["view"],
        "departments": ["view", "edit"],
        "doctors": ["view", "create", "edit"],
        "patients": ["view", "create", "edit"],
        "vitals": ["view", "create", "edit"],
        "appointments": ["view", "create", "edit"],
        "opd": list(ALL_ACTIONS),
        "emergency": ["view", "create", "edit"],
        "admissions": ["view", "create", "edit"],
        "beds": ["view", "edit"],
        "laboratory": ["view", "create"],
        "radiology": ["view", "create"],
        "pharmacy": ["view"],
        "prescriptions": ["view", "create"],
        "surgery": ["view", "create", "edit"],
        "bloodbank": ["view"],
        "documents": ["view", "create"],
        "ai": ["view"],
        "billing": ["view"],
        "insurance": ["view"],
        "inventory": ["view"],
        "staff": ["view", "edit"],
        "notifications": ["view", "edit"],
        "analytics": ["view"],
        "hospital": ["view"],
        "navigation": ["view"],
    },
    RoleCode.DOCTOR: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view", "edit"],
        "vitals": ["view", "create"],
        "appointments": ["view", "create", "edit"],
        "opd": ["view", "create", "edit"],
        "emergency": ["view", "edit"],
        "admissions": ["view", "create", "edit"],
        "beds": ["view"],
        "laboratory": ["view", "create"],
        "radiology": ["view", "create"],
        "pharmacy": ["view"],
        "prescriptions": ["view", "create", "edit"],
        "surgery": ["view", "create"],
        "bloodbank": ["view", "create"],
        "documents": ["view", "create"],
        "ai": ["view"],
        "billing": ["view"],
        "insurance": ["view"],
        "notifications": ["view", "edit"],
        "analytics": ["view"],
        "navigation": ["view"],
    },
    RoleCode.NURSE: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view"],
        "vitals": ["view", "create", "edit"],
        "appointments": ["view"],
        "opd": ["view"],
        "emergency": ["view", "edit"],
        "admissions": ["view", "edit"],
        "beds": ["view", "edit"],
        "laboratory": ["view"],
        "radiology": ["view"],
        "pharmacy": ["view"],
        "prescriptions": ["view"],
        "surgery": ["view"],
        "bloodbank": ["view"],
        "documents": ["view", "create"],
        "notifications": ["view", "edit"],
        "navigation": ["view"],
    },
    RoleCode.RECEPTIONIST: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view", "create", "edit"],
        "vitals": ["view", "create"],
        "appointments": ["view", "create", "edit", "delete"],
        "opd": ["view"],
        "emergency": ["view", "create", "edit"],
        "admissions": ["view", "create", "edit"],
        "beds": ["view"],
        "laboratory": ["view"],
        "radiology": ["view"],
        "billing": ["view", "create", "edit"],
        "insurance": ["view", "create"],
        "documents": ["view", "create"],
        "notifications": ["view", "edit"],
        "navigation": ["view"],
    },
    RoleCode.LAB_TECHNICIAN: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view"],
        "laboratory": list(ALL_ACTIONS),
        "documents": ["view", "create"],
        "notifications": ["view", "edit"],
        "navigation": ["view"],
        "analytics": ["view"],
    },
    RoleCode.RADIOLOGIST: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view"],
        "radiology": list(ALL_ACTIONS),
        "documents": ["view", "create"],
        "notifications": ["view", "edit"],
        "navigation": ["view"],
    },
    RoleCode.PHARMACIST: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view"],
        "pharmacy": list(ALL_ACTIONS),
        "prescriptions": ["view", "edit"],
        "inventory": ["view", "edit"],
        "documents": ["view"],
        "notifications": ["view", "edit"],
        "navigation": ["view"],
    },
    RoleCode.BILLING_STAFF: {
        "departments": ["view"],
        "doctors": ["view"],
        "patients": ["view"],
        "appointments": ["view"],
        "admissions": ["view"],
        "billing": list(ALL_ACTIONS),
        "insurance": ["view", "create", "edit"],
        "notifications": ["view", "edit"],
        "analytics": ["view"],
        "navigation": ["view"],
    },
    RoleCode.INSURANCE_STAFF: {
        "patients": ["view"],
        "billing": ["view"],
        "insurance": list(ALL_ACTIONS),
        "documents": ["view", "create"],
        "notifications": ["view", "edit"],
        "analytics": ["view"],
        "navigation": ["view"],
    },
    RoleCode.INVENTORY_MANAGER: {
        "departments": ["view"],
        "inventory": list(ALL_ACTIONS),
        "pharmacy": ["view", "edit"],
        "analytics": ["view"],
        "notifications": ["view", "edit"],
        "navigation": ["view"],
    },
    RoleCode.PATIENT: {
        "portal": ["view"],
        # Object-level scoping restricts this to the patient's own record only.
        "patients": ["view"],
        "documents": ["view", "create"],
        "notifications": ["view", "edit"],
        "appointments": ["view"],
        "billing": ["view"],
        "insurance": ["view"],
        "prescriptions": ["view"],
        "laboratory": ["view"],
        "radiology": ["view"],
        "ai": ["view"],
        "navigation": ["view"],
    },
}
