# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(default='ASTERNOVA', max_length=20)),
                ('hospital_type', models.CharField(default='Multispeciality Hospital', max_length=80)),
                ('established_year', models.PositiveIntegerField(default=2012)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(default='India', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('emergency_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=60)),
                ('total_beds', models.PositiveIntegerField(default=350)),
                ('icu_beds', models.PositiveIntegerField(default=40)),
                ('emergency_beds', models.PositiveIntegerField(default=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('about', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact_extension', models.CharField(blank=True, max_length=12)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bed_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_clinical', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to='doctors.doctor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('department', 'Department'), ('diagnostics', 'Diagnostics'), ('service', 'Patient Service'), ('critical', 'Critical Care'), ('facility', 'Facility'), ('support', 'Support')], default='department', max_length=30)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('keywords', models.CharField(blank=True, help_text='Extra search terms, comma separated.', max_length=250)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('is_wheelchair_accessible', models.BooleanField(default=True)),
                ('is_landmark', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_locations', to='hospital.department')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hospital.floor')),
            ],
            options={
                'ordering': ['floor__number', 'name'],
            },
        ),
    ]
