# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(max_length=20, unique=True)),
                ('admission_date', models.DateTimeField(db_index=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=20)),
                ('admission_reason', models.CharField(blank=True, max_length=300)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('treatment_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('under_treatment', 'Under Treatment'), ('ready_for_discharge', 'Ready for Discharge'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_id', models.CharField(max_length=20, unique=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis_summary', models.TextField(blank=True)),
                ('procedures', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('condition_on_discharge', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Doctor Approval'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('doctor_approved', models.BooleanField(default=False)),
                ('final_bill_settled', models.BooleanField(default=False)),
                ('pharmacy_cleared', models.BooleanField(default=False)),
                ('insurance_processed', models.BooleanField(default=False)),
                ('follow_up_scheduled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Discharge summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
