# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0003_initial'),
        ('billing', '0001_initial'),
        ('doctors', '0002_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_summaries', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='final_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_summaries', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status', 'department'], name='admissions__status_f220ec_idx'),
        ),
    ]
