# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('general', 'General Ward'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('icu', 'ICU'), ('emergency', 'Emergency'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('isolation', 'Isolation')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Cleaning')], db_index=True, default='available', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_oxygen', models.BooleanField(default=True)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('is_monitored', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(choices=[('general', 'General Ward'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('icu', 'ICU'), ('emergency', 'Emergency'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('isolation', 'Isolation')], default='general', max_length=20)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
