# Reference catalogues for the fictional AsterNova demo hospital.

from .names import DEPARTMENT_DESCRIPTIONS

DEPARTMENTS = [
    {
        "name": "Cardiology",
        "code": "CARD",
        "floor": "2nd Floor",
        "location": "C-Wing, Block C",
        "extension": "2201",
        "beds": 30,
        "hod": {
            "name": "Dr. Arjun Menon",
            "qualification": "MBBS, MD (Medicine), DM (Cardiology)",
            "experience": 18,
            "room": "C-201",
            "specialization": "Interventional Cardiology",
        },
    },
    {
        "name": "Neurology",
        "code": "NEUR",
        "floor": "2nd Floor",
        "location": "N-Wing, Block B",
        "extension": "2202",
        "beds": 24,
        "hod": {
            "name": "Dr. Meera Nair",
            "qualification": "MBBS, MD (Medicine), DM (Neurology)",
            "experience": 16,
            "room": "N-202",
            "specialization": "Epilepsy and Stroke Medicine",
        },
    },
    {
        "name": "Orthopedics",
        "code": "ORTH",
        "floor": "1st Floor",
        "location": "O-Wing, Block A",
        "extension": "1105",
        "beds": 26,
        "hod": {
            "name": "Dr. Rahul Varma",
            "qualification": "MBBS, MS (Orthopedics)",
            "experience": 15,
            "room": "O-105",
            "specialization": "Joint Replacement and Arthroscopy",
        },
    },
    {
        "name": "General Medicine",
        "code": "GMED",
        "floor": "1st Floor",
        "location": "A-Wing, Block A",
        "extension": "1101",
        "beds": 40,
        "hod": {
            "name": "Dr. Anjali Krishnan",
            "qualification": "MBBS, MD (General Medicine)",
            "experience": 14,
            "room": "GM-101",
            "specialization": "Diabetes and Internal Medicine",
        },
    },
    {
        "name": "General Surgery",
        "code": "GSUR",
        "floor": "1st Floor",
        "location": "S-Wing, Block A",
        "extension": "1110",
        "beds": 32,
        "hod": {
            "name": "Dr. Vivek Menon",
            "qualification": "MBBS, MS (General Surgery)",
            "experience": 17,
            "room": "GS-110",
            "specialization": "Laparoscopic Surgery",
        },
    },
    {
        "name": "Pediatrics",
        "code": "PEDI",
        "floor": "2nd Floor",
        "location": "P-Wing, Block C",
        "extension": "2204",
        "beds": 28,
        "hod": {
            "name": "Dr. Diya Thomas",
            "qualification": "MBBS, MD (Pediatrics)",
            "experience": 12,
            "room": "P-204",
            "specialization": "Neonatology and Pediatric Intensive Care",
        },
    },
    {
        "name": "Gynecology",
        "code": "GYNE",
        "floor": "3rd Floor",
        "location": "G-Wing, Block D",
        "extension": "3301",
        "beds": 24,
        "hod": {
            "name": "Dr. Sneha Mathew",
            "qualification": "MBBS, MD (Obstetrics & Gynecology)",
            "experience": 13,
            "room": "G-301",
            "specialization": "Minimally Invasive Gynecology",
        },
    },
    {
        "name": "Obstetrics",
        "code": "OBST",
        "floor": "3rd Floor",
        "location": "Maternity Block D",
        "extension": "3302",
        "beds": 26,
        "hod": {
            "name": "Dr. Reshma Pillai",
            "qualification": "MBBS, MS (Obstetrics & Gynecology)",
            "experience": 15,
            "room": "G-305",
            "specialization": "High Risk Pregnancy",
        },
    },
    {
        "name": "Dermatology",
        "code": "DERM",
        "floor": "1st Floor",
        "location": "D-Wing, Block B",
        "extension": "1210",
        "beds": 10,
        "hod": {
            "name": "Dr. Lakshmi Warrier",
            "qualification": "MBBS, MD (Dermatology)",
            "experience": 11,
            "room": "D-112",
            "specialization": "Clinical Dermatology and Phototherapy",
        },
    },
    {
        "name": "ENT",
        "code": "ENTS",
        "floor": "2nd Floor",
        "location": "E-Wing, Block B",
        "extension": "2215",
        "beds": 14,
        "hod": {
            "name": "Dr. Sreejith Nambiar",
            "qualification": "MBBS, MS (ENT)",
            "experience": 13,
            "room": "E-208",
            "specialization": "Endoscopic Sinus Surgery",
        },
    },
    {
        "name": "Ophthalmology",
        "code": "OPHT",
        "floor": "1st Floor",
        "location": "E-Wing, Block B",
        "extension": "1220",
        "beds": 12,
        "hod": {
            "name": "Dr. Divya Nair",
            "qualification": "MBBS, MS (Ophthalmology)",
            "experience": 12,
            "room": "E-118",
            "specialization": "Cataract and Refractive Surgery",
        },
    },
    {
        "name": "Oncology",
        "code": "ONCO",
        "floor": "4th Floor",
        "location": "ON-Wing, Block E",
        "extension": "4401",
        "beds": 22,
        "hod": {
            "name": "Dr. Nikhil Joseph",
            "qualification": "MBBS, MD (Medicine), DM (Medical Oncology)",
            "experience": 19,
            "room": "ON-401",
            "specialization": "Medical Oncology and Haemato-Oncology",
        },
    },
    {
        "name": "Nephrology",
        "code": "NEPH",
        "floor": "3rd Floor",
        "location": "N-Wing, Block C",
        "extension": "3310",
        "beds": 18,
        "hod": {
            "name": "Dr. Harish Balakrishnan",
            "qualification": "MBBS, MD (Medicine), DM (Nephrology)",
            "experience": 16,
            "room": "N-310",
            "specialization": "Dialysis and Transplant Medicine",
        },
    },
    {
        "name": "Gastroenterology",
        "code": "GAST",
        "floor": "2nd Floor",
        "location": "G-Wing, Block C",
        "extension": "2225",
        "beds": 16,
        "hod": {
            "name": "Dr. Anand Varghese",
            "qualification": "MBBS, MD (Medicine), DM (Gastroenterology)",
            "experience": 14,
            "room": "G-215",
            "specialization": "Therapeutic Endoscopy and Hepatology",
        },
    },
    {
        "name": "Pulmonology",
        "code": "PULM",
        "floor": "2nd Floor",
        "location": "P-Wing, Block B",
        "extension": "2230",
        "beds": 18,
        "hod": {
            "name": "Dr. Manoj Sasidharan",
            "qualification": "MBBS, MD (Pulmonary Medicine)",
            "experience": 13,
            "room": "P-221",
            "specialization": "Interventional Pulmonology and Sleep Medicine",
        },
    },
    {
        "name": "Psychiatry",
        "code": "PSYC",
        "floor": "3rd Floor",
        "location": "B-Wing, Block D",
        "extension": "3320",
        "beds": 14,
        "hod": {
            "name": "Dr. Anjana Raghunath",
            "qualification": "MBBS, MD (Psychiatry)",
            "experience": 12,
            "room": "B-320",
            "specialization": "Adult Psychiatry and De-addiction",
        },
    },
    {
        "name": "Emergency Medicine",
        "code": "EMER",
        "floor": "Ground Floor",
        "location": "Emergency Block, Gate 1",
        "extension": "1001",
        "beds": 20,
        "hod": {
            "name": "Dr. Ranjith Mohan",
            "qualification": "MBBS, MD (Emergency Medicine)",
            "experience": 13,
            "room": "ER-101",
            "specialization": "Trauma and Critical Care",
        },
    },
    {
        "name": "Radiology",
        "code": "RADI",
        "floor": "Ground Floor",
        "location": "Diagnostics Block",
        "extension": "1010",
        "beds": 0,
        "is_clinical": False,
        "hod": {
            "name": "Dr. Sandeep Kurup",
            "qualification": "MBBS, MD (Radiodiagnosis)",
            "experience": 15,
            "room": "RD-105",
            "specialization": "Cross-sectional Imaging",
        },
    },
    {
        "name": "Pathology",
        "code": "PATH",
        "floor": "Ground Floor",
        "location": "Diagnostics Block",
        "extension": "1015",
        "beds": 0,
        "is_clinical": False,
        "hod": {
            "name": "Dr. Geethu Chandran",
            "qualification": "MBBS, MD (Pathology)",
            "experience": 14,
            "room": "LB-110",
            "specialization": "Clinical Pathology and Haematology",
        },
    },
    {
        "name": "Anesthesiology",
        "code": "ANES",
        "floor": "1st Floor",
        "location": "Operation Theatre Complex",
        "extension": "1301",
        "beds": 0,
        "is_clinical": False,
        "hod": {
            "name": "Dr. Vinod Krishnakumar",
            "qualification": "MBBS, MD (Anaesthesiology)",
            "experience": 17,
            "room": "OT-131",
            "specialization": "Cardiac and Neuro Anaesthesia",
        },
    },
]

for _department in DEPARTMENTS:
    _department["description"] = DEPARTMENT_DESCRIPTIONS.get(_department["name"], "")
    _department.setdefault("is_clinical", True)

SHIFTS = [
    {
        "name": "Morning",
        "code": "MORN",
        "start_time": "07:00",
        "end_time": "15:00",
        "description": "Primary clinical shift covering morning outpatient clinics.",
        "is_emergency_shift": False,
        "color": "#2563eb",
    },
    {
        "name": "Afternoon",
        "code": "AFTN",
        "start_time": "15:00",
        "end_time": "23:00",
        "description": "Evening outpatient clinics and ward handover.",
        "is_emergency_shift": False,
        "color": "#0891b2",
    },
    {
        "name": "Night",
        "code": "NGHT",
        "start_time": "23:00",
        "end_time": "07:00",
        "description": "Night duty with resident medical officers on call.",
        "is_emergency_shift": False,
        "color": "#4338ca",
    },
    {
        "name": "Emergency",
        "code": "EMRG",
        "start_time": "08:00",
        "end_time": "20:00",
        "description": "Emergency department and ambulance response shift.",
        "is_emergency_shift": True,
        "color": "#dc2626",
    },
]

LAB_TESTS = [
    ("LAB-CBC", "Complete Blood Count (CBC)", "hematology", "Blood", "", "13.5 - 17.5 g/dL (Hb)", 4, 450),
    ("LAB-ESR", "Erythrocyte Sedimentation Rate", "hematology", "Blood", "mm/hr", "0 - 20 mm/hr", 4, 250),
    ("LAB-BG", "Blood Glucose - Fasting", "biochemistry", "Blood", "mg/dL", "70 - 100 mg/dL", 2, 180),
    ("LAB-BGPP", "Blood Glucose - Postprandial", "biochemistry", "Blood", "mg/dL", "70 - 140 mg/dL", 2, 200),
    ("LAB-HBA1C", "HbA1c", "biochemistry", "Blood", "%", "4.0 - 5.6 %", 24, 700),
    ("LAB-LIPID", "Lipid Profile", "biochemistry", "Blood", "mg/dL", "Total cholesterol 125 - 200 mg/dL", 12, 850),
    ("LAB-LFT", "Liver Function Test", "biochemistry", "Blood", "U/L", "SGPT 7 - 56 U/L", 12, 900),
    ("LAB-RFT", "Kidney Function Test", "biochemistry", "Blood", "mg/dL", "Creatinine 0.6 - 1.3 mg/dL", 12, 850),
    ("LAB-THY", "Thyroid Profile (T3, T4, TSH)", "hormone", "Blood", "mIU/L", "TSH 0.4 - 4.0 mIU/L", 24, 950),
    ("LAB-URINE", "Urine Routine Examination", "urine", "Urine", "", "Specific gravity 1.005 - 1.030", 6, 300),
    ("LAB-ELEC", "Serum Electrolytes", "biochemistry", "Blood", "mmol/L", "Sodium 135 - 145 mmol/L", 4, 650),
    ("LAB-CRP", "C-Reactive Protein (CRP)", "serology", "Blood", "mg/L", "0 - 5 mg/L", 6, 700),
    ("LAB-VITD", "Vitamin D (25-OH)", "hormone", "Blood", "ng/mL", "30 - 100 ng/mL", 48, 1400),
    ("LAB-VITB12", "Vitamin B12", "hormone", "Blood", "pg/mL", "211 - 911 pg/mL", 48, 1250),
    ("LAB-TROPI", "Troponin I", "cardiac", "Blood", "ng/mL", "0 - 0.04 ng/mL", 2, 1500),
    ("LAB-DDIMER", "D-Dimer", "hematology", "Blood", "ng/mL", "0 - 500 ng/mL", 6, 1800),
    ("LAB-WIDAL", "Widal Test", "serology", "Blood", "titre", "Negative", 24, 400),
    ("LAB-COVID", "Respiratory Viral Panel", "microbiology", "Nasopharyngeal swab", "", "Negative", 24, 2200),
    ("LAB-BIOP", "Histopathology - Biopsy", "pathology", "Tissue", "", "Report issued by pathologist", 72, 3500),
    ("LAB-PSA", "Prostate Specific Antigen", "biochemistry", "Blood", "ng/mL", "0 - 4 ng/mL", 24, 1100),
]

# Supplier, inventory and pharmacy catalogues ---------------------------------
#
# Every manufacturer, supplier and insurer below is a fictional entity created
# for this demonstration.

SUPPLIERS = [
    ("SUP-1001", "Kerala Medisys Supplies", "Ramesh Varma", "+91 484 220 1101", "sales@kerelamedisys.demo", "Medical equipment", "Kochi, Kerala"),
    ("SUP-1002", "Coastal Pharma Distributors", "Anitha Nair", "+91 484 220 1102", "orders@coastalpharma.demo", "Pharmaceuticals", "Aluva, Kerala"),
    ("SUP-1003", "SafeGuard PPE India", "Vinod Pillai", "+91 484 220 1103", "contact@safeguardppe.demo", "PPE and disposables", "Kakkanad, Kerala"),
    ("SUP-1004", "Precision Lab Systems", "Fathima Rasheed", "+91 484 220 1104", "support@precisionlab.demo", "Laboratory supplies", "Ernakulam, Kerala"),
    ("SUP-1005", "Sterling Surgical Instruments", "George Mathew", "+91 484 220 1105", "sales@sterlingsurgical.demo", "Surgical instruments", "Thrissur, Kerala"),
    ("SUP-1006", "Nova Office Solutions", "Deepa Krishnan", "+91 484 220 1106", "hello@novaoffice.demo", "Office supplies", "Kochi, Kerala"),
    ("SUP-1007", "LifeLine Biomedical Services", "Suresh Kumar", "+91 484 220 1107", "service@lifelinebio.demo", "Equipment maintenance", "Kalamassery, Kerala"),
    ("SUP-1008", "GreenClean Facility Supplies", "Manju Raghunath", "+91 484 220 1108", "orders@greenclean.demo", "Housekeeping", "Vyttila, Kerala"),
]

# (name, generic, category, manufacturer, unit, price, cost, stock, reorder,
#  expiry_days_from_today, prescription_required)
MEDICINES = [
    ("Paracetamol 500 mg Tablet", "Paracetamol", "analgesic", "Coastal Pharma Labs", "tablet", 2.50, 1.20, 1250, 200, 420, False),
    ("Ibuprofen 400 mg Tablet", "Ibuprofen", "analgesic", "Coastal Pharma Labs", "tablet", 4.00, 2.10, 860, 150, 380, True),
    ("Tramadol 50 mg Capsule", "Tramadol", "analgesic", "Meridian Generics", "capsule", 9.50, 5.40, 180, 60, 300, True),
    ("Amoxicillin 500 mg Capsule", "Amoxicillin", "antibiotic", "Meridian Generics", "capsule", 8.50, 4.60, 640, 120, 260, True),
    ("Azithromycin 500 mg Tablet", "Azithromycin", "antibiotic", "Coastal Pharma Labs", "tablet", 24.00, 15.00, 140, 60, 240, True),
    ("Ceftriaxone 1 g Injection", "Ceftriaxone", "antibiotic", "Sterling Biocare", "vial", 78.00, 52.00, 95, 40, 200, True),
    ("Metronidazole 400 mg Tablet", "Metronidazole", "antibiotic", "Meridian Generics", "tablet", 3.60, 1.90, 420, 100, 330, True),
    ("Atorvastatin 10 mg Tablet", "Atorvastatin", "cardiovascular", "Novacare Pharma", "tablet", 6.80, 3.40, 720, 150, 400, True),
    ("Amlodipine 5 mg Tablet", "Amlodipine", "cardiovascular", "Novacare Pharma", "tablet", 3.20, 1.60, 980, 200, 410, True),
    ("Telmisartan 40 mg Tablet", "Telmisartan", "cardiovascular", "Novacare Pharma", "tablet", 7.40, 3.90, 610, 150, 350, True),
    ("Metoprolol 25 mg Tablet", "Metoprolol", "cardiovascular", "Sterling Biocare", "tablet", 5.20, 2.70, 380, 120, 300, True),
    ("Clopidogrel 75 mg Tablet", "Clopidogrel", "cardiovascular", "Novacare Pharma", "tablet", 8.90, 4.80, 265, 100, 280, True),
    ("Furosemide 40 mg Tablet", "Furosemide", "cardiovascular", "Meridian Generics", "tablet", 3.10, 1.50, 45, 80, 260, True),
    ("Metformin 500 mg Tablet", "Metformin", "antidiabetic", "Coastal Pharma Labs", "tablet", 3.40, 1.70, 1120, 200, 390, True),
    ("Glimepiride 2 mg Tablet", "Glimepiride", "antidiabetic", "Novacare Pharma", "tablet", 6.10, 3.20, 480, 120, 320, True),
    ("Insulin Human 100 IU/mL", "Insulin Human", "antidiabetic", "Sterling Biocare", "vial", 320.00, 245.00, 60, 40, 150, True),
    ("Salbutamol Inhaler", "Salbutamol", "respiratory", "AeroCare Devices", "inhaler", 185.00, 132.00, 88, 40, 280, True),
    ("Montelukast 10 mg Tablet", "Montelukast", "respiratory", "AeroCare Devices", "tablet", 11.50, 6.40, 240, 80, 300, True),
    ("Pantoprazole 40 mg Tablet", "Pantoprazole", "gastrointestinal", "Meridian Generics", "tablet", 5.60, 2.80, 730, 150, 340, True),
    ("Ondansetron 4 mg Tablet", "Ondansetron", "gastrointestinal", "Coastal Pharma Labs", "tablet", 6.40, 3.30, 310, 100, 290, True),
    ("ORS Sachet", "Oral Rehydration Salts", "gastrointestinal", "Coastal Pharma Labs", "sachet", 12.00, 6.50, 0, 150, 500, False),
    ("Levetiracetam 500 mg Tablet", "Levetiracetam", "neurological", "Novacare Pharma", "tablet", 14.50, 8.60, 210, 80, 300, True),
    ("Phenytoin 100 mg Tablet", "Phenytoin", "neurological", "Meridian Generics", "tablet", 4.80, 2.40, 160, 60, 270, True),
    ("Amitriptyline 10 mg Tablet", "Amitriptyline", "neurological", "Sterling Biocare", "tablet", 3.90, 1.95, 55, 60, 260, True),
    ("Levothyroxine 50 mcg Tablet", "Levothyroxine", "vitamin", "Novacare Pharma", "tablet", 4.20, 2.10, 640, 150, 330, True),
    ("Vitamin D3 60K Sachet", "Cholecalciferol", "vitamin", "Sterling Biocare", "sachet", 32.00, 19.00, 390, 100, 400, False),
    ("Ferrous Ascorbate + Folic Acid", "Ferrous Ascorbate", "vitamin", "Coastal Pharma Labs", "tablet", 5.10, 2.60, 520, 120, 350, False),
    ("Cefixime 200 mg Tablet", "Cefixime", "antibiotic", "Meridian Generics", "tablet", 15.00, 9.20, 85, 60, 220, True),
    ("Human Albumin 20%", "Human Albumin", "iv_fluid", "Sterling Biocare", "bottle", 4200.00, 3400.00, 18, 20, 180, True),
    ("Normal Saline 500 mL", "Sodium Chloride 0.9%", "iv_fluid", "Kerala Medisys Supplies", "bottle", 62.00, 41.00, 740, 200, 400, False),
    ("Ringer Lactate 500 mL", "Ringer Lactate", "iv_fluid", "Kerala Medisys Supplies", "bottle", 68.00, 45.00, 615, 200, 400, False),
    ("Dextrose 25% 100 mL", "Dextrose", "iv_fluid", "Kerala Medisys Supplies", "bottle", 88.00, 58.00, 150, 80, 330, False),
    ("Clotrimazole 1% Cream", "Clotrimazole", "topical", "Coastal Pharma Labs", "tube", 78.00, 46.00, 265, 80, 300, False),
    ("Mupirocin 2% Ointment", "Mupirocin", "topical", "Sterling Biocare", "tube", 145.00, 96.00, 130, 60, 280, True),
    ("Tetanus Toxoid Vaccine", "Tetanus Toxoid", "vaccine", "Sterling Biocare", "dose", 210.00, 155.00, 96, 40, 240, True),
    ("Hepatitis B Vaccine", "Hepatitis B", "vaccine", "Sterling Biocare", "dose", 480.00, 355.00, 42, 30, 210, True),
    ("Carboplatin 150 mg Injection", "Carboplatin", "other", "OncoLife Therapeutics", "vial", 3250.00, 2450.00, 22, 15, 190, True),
    ("Tamoxifen 20 mg Tablet", "Tamoxifen", "other", "OncoLife Therapeutics", "tablet", 18.50, 11.20, 175, 60, 320, True),
    ("Rituximab 500 mg Infusion", "Rituximab", "other", "OncoLife Therapeutics", "vial", 18500.00, 14600.00, 9, 10, 240, True),
    ("Ondansetron 2 mg/mL Injection", "Ondansetron", "gastrointestinal", "Coastal Pharma Labs", "ampoule", 28.00, 17.00, 210, 80, 260, True),
]

# (name, category, unit, stock, reorder, unit_price, location, expiry_days)
INVENTORY_ITEMS = [
    ("Nitrile Examination Gloves (M)", "ppe", "box", 420, 150, 480.00, "Central Store A1", None),
    ("N95 Respirator Mask", "ppe", "box", 165, 80, 1250.00, "Central Store A1", None),
    ("Surgical Face Mask - 3 Ply", "ppe", "pack", 640, 200, 210.00, "Central Store A1", None),
    ("Sterile Gauze Swabs 10x10", "surgical_supplies", "pack", 520, 200, 145.00, "Surgical Store B2", 700),
    ("Disposable Syringe 5 mL", "surgical_supplies", "box", 310, 150, 620.00, "Surgical Store B2", None),
    ("IV Cannula 20G", "surgical_supplies", "box", 85, 100, 890.00, "Surgical Store B2", 620),
    ("Surgical Suture 3-0", "surgical_supplies", "box", 140, 60, 1350.00, "Surgical Store B2", 540),
    ("Urinary Catheter 16Fr", "surgical_supplies", "unit", 210, 100, 165.00, "Surgical Store B3", 480),
    ("Endotracheal Tube 7.5 mm", "surgical_supplies", "unit", 45, 60, 320.00, "ICU Store C1", 500),
    ("Blood Collection Tube - EDTA", "laboratory_supplies", "pack", 380, 150, 420.00, "Laboratory Store D1", 420),
    ("Blood Collection Tube - Plain", "laboratory_supplies", "pack", 340, 150, 400.00, "Laboratory Store D1", 420),
    ("Microscope Slides", "laboratory_supplies", "pack", 260, 100, 310.00, "Laboratory Store D1", None),
    ("Reagent - Glucose Oxidase", "laboratory_supplies", "kit", 34, 40, 2450.00, "Laboratory Store D2", 180),
    ("Reagent - Haematology Diluent", "laboratory_supplies", "bottle", 28, 30, 1850.00, "Laboratory Store D2", 210),
    ("Rapid Antigen Test Kit", "laboratory_supplies", "box", 96, 60, 980.00, "Laboratory Store D2", 150),
    ("CT Contrast Media 100 mL", "medical_equipment", "bottle", 42, 30, 2650.00, "Radiology Store E1", 240),
    ("Portable Oxygen Cylinder", "medical_equipment", "unit", 26, 15, 5400.00, "Central Store A2", None),
    ("Infusion Pump", "medical_equipment", "unit", 38, 10, 32500.00, "Equipment Store A3", None),
    ("Digital Blood Pressure Monitor", "medical_equipment", "unit", 54, 20, 3200.00, "Equipment Store A3", None),
    ("Pulse Oximeter", "medical_equipment", "unit", 78, 25, 1850.00, "Equipment Store A3", None),
    ("Cardiac Monitor - Multiparameter", "medical_equipment", "unit", 12, 6, 185000.00, "ICU Store C1", None),
    ("Wheelchair Folding", "medical_equipment", "unit", 19, 8, 7800.00, "Equipment Store A4", None),
    ("Disposable Bed Sheet Roll", "housekeeping", "roll", 180, 80, 640.00, "Housekeeping Store H1", None),
    ("Surface Disinfectant 5 L", "housekeeping", "can", 64, 40, 890.00, "Housekeeping Store H1", 330),
    ("Hand Sanitiser 500 mL", "housekeeping", "bottle", 240, 100, 210.00, "Housekeeping Store H1", 400),
    ("A4 Printing Paper", "office_supplies", "ream", 145, 60, 320.00, "Admin Store F1", None),
    ("Medical Record Folder", "office_supplies", "pack", 92, 50, 480.00, "Admin Store F1", None),
    ("Thermal Printer Roll", "office_supplies", "box", 70, 40, 760.00, "Admin Store F1", None),
]

INSURANCE_PROVIDERS = [
    ("Nova Health Assure", "NOVA", "Priya Chandran", "+91 484 330 1001", "claims@novahealth.demo"),
    ("Bharat Life Secure", "BHLS", "Ajith Rajan", "+91 484 330 1002", "claims@bharatlife.demo"),
    ("Coastal Care Insurance", "CCIN", "Remya Suresh", "+91 484 330 1003", "support@coastalcare.demo"),
    ("MediShield General", "MDSG", "Faisal Irfan", "+91 484 330 1004", "claims@medishield.demo"),
    ("Aster Star Health Plan", "ASTR", "Nithin Gopinath", "+91 484 330 1005", "claims@asterstar.demo"),
    ("Unity Corporate Health", "UNIT", "Shilpa Narayanan", "+91 484 330 1006", "corporate@unityhealth.demo"),
    ("Pragati Employees Scheme", "PRGT", "Vijay Anand", "+91 484 330 1007", "scheme@pragati.demo"),
    ("Kerala Care Benefit Fund", "KLCB", "Omana Vijayan", "+91 484 330 1008", "benefits@keralacare.demo"),
]

# Indoor navigation -----------------------------------------------------------
#
# Coordinates are on a simple 1000 x 700 virtual grid per floor so the frontend
# can draw a schematic plan and a route without a mapping provider.

FLOORS = [
    (0, "Ground Floor - Emergency & Diagnostics", "Emergency, imaging, laboratory, pharmacy and main reception."),
    (1, "First Floor - Surgery & Specialities", "Operation theatres, general surgery, orthopedics and ophthalmology clinics."),
    (2, "Second Floor - Medicine & Cardiology", "Cardiology, neurology, gastroenterology, pulmonology and ENT clinics."),
    (3, "Third Floor - Women & Child Care", "Maternity, obstetrics, gynecology, nephrology and psychiatry."),
    (4, "Fourth Floor - Oncology & Day Care", "Medical oncology, day-care chemotherapy and isolation rooms."),
]

# (floor, name, code, category, department_code, x, y, description, keywords,
#  wheelchair_accessible, is_landmark)
MAP_LOCATIONS = [
    (0, "Main Reception", "RCP-01", "service", None, 500, 620, "Patient information and registration desk.", "reception, front desk, registration, help", True, True),
    (0, "Emergency Department", "EMR-01", "critical", "EMER", 160, 520, "24x7 emergency and trauma care entrance.", "emergency, casualty, trauma, ambulance", True, True),
    (0, "Triage Bay", "EMR-02", "critical", "EMER", 250, 470, "Initial assessment and prioritisation area.", "triage, emergency", True, False),
    (0, "Resuscitation Bay", "EMR-03", "critical", "EMER", 320, 520, "Critical resuscitation and stabilisation.", "resuscitation, code blue, critical", True, False),
    (0, "Laboratory", "LB-01", "diagnostics", "PATH", 700, 520, "Sample collection and pathology services.", "lab, laboratory, blood test, pathology, sample", True, True),
    (0, "Laboratory Sample Collection", "LB-02", "diagnostics", "PATH", 660, 570, "Walk-in sample collection counter.", "sample collection, phlebotomy", True, False),
    (0, "Radiology & Imaging", "RD-01", "diagnostics", "RADI", 830, 520, "X-ray, CT, MRI and ultrasound services.", "radiology, x-ray, ct, mri, scan, ultrasound, imaging", True, True),
    (0, "CT Scan Suite", "RD-02", "diagnostics", "RADI", 880, 580, "Computed tomography scanning.", "ct, scan, imaging", True, False),
    (0, "Pharmacy", "PH-01", "service", "GMED", 560, 430, "Inpatient and outpatient pharmacy counter.", "pharmacy, medicines, drugs, chemist", True, True),
    (0, "Billing & Cash Counter", "BL-01", "service", None, 430, 620, "Invoice payments and insurance help desk.", "billing, cash, payment, invoice", True, True),
    (0, "Blood Bank", "BB-01", "diagnostics", None, 300, 330, "Blood grouping, cross match and issue counter.", "blood bank, transfusion, donation", True, True),
    (0, "Ambulance Bay", "AM-01", "facility", None, 90, 640, "Ambulance parking and patient transfer point.", "ambulance, vehicle, pickup", True, False),
    (0, "Main Lift Lobby", "LF-00", "facility", None, 500, 500, "Access to all upper floors.", "lift, elevator, floor access", True, True),
    (0, "Security Desk", "SC-01", "support", None, 380, 660, "Visitor passes and lost property.", "security, visitors, pass", True, False),
    (1, "Operation Theatre Complex", "OT-01", "critical", "GSUR", 260, 400, "Six modular theatres with recovery bay.", "operation theatre, ot, surgery, theatre", True, True),
    (1, "Pre-operative Holding Area", "OT-02", "critical", "ANES", 340, 350, "Pre-anaesthetic preparation area.", "pre-op, anaesthesia, holding", True, False),
    (1, "Post Anaesthesia Care Unit", "OT-03", "critical", "ANES", 340, 450, "Recovery and monitoring after surgery.", "pac u, recovery, post-op", True, False),
    (1, "General Surgery Clinic", "GS-110", "department", "GSUR", 620, 380, "Outpatient surgical consultation.", "general surgery, consultation", True, False),
    (1, "Orthopedics Clinic", "OR-105", "department", "ORTH", 620, 470, "Bone, joint and sports injury clinic.", "orthopedics, bone, joint, fracture", True, False),
    (1, "Ophthalmology Clinic", "OP-118", "department", "OPHT", 780, 380, "Eye clinic with refraction and procedure room.", "eye, ophthalmology, vision", True, False),
    (1, "Dermatology Clinic", "DR-112", "department", "DERM", 780, 470, "Skin, hair and nail clinic.", "dermatology, skin, hair, allergy", True, False),
    (1, "First Floor Lift Lobby", "LF-01", "facility", None, 500, 420, "Access to ground floor lift lobby.", "lift, elevator", True, False),
    (2, "Cardiology Clinic", "CD-201", "department", "CARD", 250, 380, "Cardiac consultation, ECG and echocardiography.", "cardiology, heart, ecg, echo", True, True),
    (2, "Cardiac Cath Lab", "CD-210", "critical", "CARD", 180, 470, "Angiography and interventional procedures.", "cath lab, angiography, angioplasty", True, False),
    (2, "Neurology Clinic", "NR-202", "department", "NEUR", 470, 380, "Neurology consultation and EEG room.", "neurology, brain, nerves, eeg", True, True),
    (2, "Gastroenterology Clinic", "GE-215", "department", "GAST", 690, 380, "Digestive health and endoscopy suite.", "gastro, endoscopy, liver, stomach", True, False),
    (2, "Pulmonology Clinic", "PU-221", "department", "PULM", 690, 470, "Respiratory clinic and pulmonary function lab.", "pulmonology, lungs, breathing, spirometry", True, False),
    (2, "ENT Clinic", "EN-208", "department", "ENTS", 470, 470, "Ear, nose and throat clinic with audiology.", "ent, ear, nose, throat, hearing", True, False),
    (2, "ICU - Medical", "IC-01", "critical", None, 880, 300, "Twelve bed medical intensive care unit.", "icu, intensive care, critical", True, True),
    (3, "Maternity Ward", "MT-301", "department", "OBST", 250, 380, "Labour rooms and postnatal beds.", "maternity, labour, delivery, pregnancy", True, True),
    (3, "Gynecology Clinic", "GY-305", "department", "GYNE", 250, 470, "Women's health consultation.", "gynecology, women, pcos", True, False),
    (3, "Nephrology & Dialysis", "NP-310", "department", "NEPH", 540, 380, "Dialysis unit with twelve stations.", "nephrology, kidney, dialysis", True, True),
    (3, "Psychiatry Clinic", "PS-320", "department", "PSYC", 760, 380, "Confidential mental health consultation.", "psychiatry, mental health, counselling", True, False),
    (3, "Neonatal ICU", "IC-03", "critical", "PEDI", 760, 470, "Level-3 neonatal intensive care.", "nicu, neonatal, newborn", True, False),
    (4, "Medical Oncology Day Care", "ON-401", "department", "ONCO", 260, 380, "Chemotherapy day-care with sixteen chairs.", "oncology, cancer, chemotherapy", True, True),
    (4, "Radiation Oncology", "ON-410", "department", "ONCO", 260, 470, "Linear accelerator and planning suite.", "radiation, radiotherapy, linac", True, False),
    (4, "Isolation Ward", "IS-420", "critical", None, 620, 380, "Negative pressure isolation rooms.", "isolation, infection, negative pressure", True, False),
    (4, "Fourth Floor Lift Lobby", "LF-04", "facility", None, 620, 520, "Access to day-care and oncology wards.", "lift, elevator", True, False),
]
