# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=20, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('ward', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('crossmatch_id', models.CharField(blank=True, max_length=40)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('issued', 'Issued'), ('transfused', 'Transfused'), ('returned', 'Returned'), ('discarded', 'Discarded')], default='reserved', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('is_demo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, unique=True)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('units_reserved', models.PositiveIntegerField(default=0)),
                ('critical_threshold', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blood stock',
                'ordering': ['blood_group'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(max_length=20, unique=True)),
                ('donor_name', models.CharField(max_length=140)),
                ('donor_code', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('donation_date', models.DateField(db_index=True)),
                ('donor_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('donor_gender', models.CharField(blank=True, max_length=10)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('camp_location', models.CharField(blank=True, max_length=140)),
                ('screening', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Screening Passed'), ('failed', 'Screening Failed')], default='passed', max_length=20)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
