# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('hospital', '0001_initial'),
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_id', models.CharField(max_length=20, unique=True)),
                ('surgery_name', models.CharField(max_length=200)),
                ('procedure_code', models.CharField(blank=True, max_length=30)),
                ('ot_room', models.CharField(max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('anesthesia_type', models.CharField(choices=[('general', 'General'), ('spinal', 'Spinal'), ('epidural', 'Epidural'), ('regional', 'Regional Block'), ('local', 'Local'), ('sedation', 'Conscious Sedation')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('preparing', 'Preparing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('blood_units_reserved', models.PositiveSmallIntegerField(default=0)),
                ('pre_op_notes', models.TextField(blank=True)),
                ('post_op_notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthetist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_cases', to='doctors.doctor')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='hospital.department')),
                ('nurses', models.ManyToManyField(blank=True, related_name='surgery_assists', to='staff.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries_performed', to='doctors.doctor')),
            ],
            options={
                'verbose_name_plural': 'Surgeries',
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'status'], name='surgery_sur_date_d2ca55_idx')],
            },
        ),
    ]
