# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('designation', models.CharField(choices=[('hod', 'HOD & Senior Consultant'), ('senior_consultant', 'Senior Consultant'), ('consultant', 'Consultant'), ('associate_consultant', 'Associate Consultant'), ('registrar', 'Registrar'), ('resident', 'Resident Medical Officer'), ('visiting', 'Visiting Consultant')], default='consultant', max_length=40)),
                ('is_hod', models.BooleanField(default=False)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('phone_extension', models.CharField(blank=True, max_length=12)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('in_consultation', 'In Consultation'), ('in_surgery', 'In Surgery'), ('on_rounds', 'On Rounds'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('available_days', models.CharField(blank=True, max_length=120)),
                ('opd_schedule', models.JSONField(blank=True, default=dict, help_text="Weekday -> list of consultation slots, e.g. {'mon': ['09:00-13:00']}")),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=120)),
                ('about', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
