# Generated by Django 6.1.1 on 2026-09-28 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('medical_equipment', 'Medical Equipment'), ('surgical_supplies', 'Surgical Supplies'), ('ppe', 'PPE'), ('laboratory_supplies', 'Laboratory Supplies'), ('medicines', 'Medicines'), ('office_supplies', 'Office Supplies'), ('housekeeping', 'Housekeeping'), ('it_equipment', 'IT Equipment')], default='surgical_supplies', max_length=30)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('batch_number', models.CharField(blank=True, max_length=40)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('discontinued', 'Discontinued')], default='available', max_length=20)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('disposal', 'Disposal')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('balance_after', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('tax_id', models.CharField(blank=True, max_length=40)),
                ('payment_terms', models.CharField(blank=True, default='Net 30', max_length=80)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
