# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('insurance', '0001_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insuranceprovider'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['status'], name='insurance_i_status_497753_idx'),
        ),
    ]
