# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology'), ('pathology', 'Pathology'), ('urine', 'Urine Analysis'), ('hormone', 'Hormone Assay'), ('cardiac', 'Cardiac Markers')], default='biochemistry', max_length=30)),
                ('sample_type', models.CharField(default='Blood', max_length=60)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('reference_range', models.CharField(blank=True, max_length=80)),
                ('turnaround_hours', models.PositiveSmallIntegerField(default=24)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=20, unique=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=250)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('reference_range', models.CharField(blank=True, max_length=80)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('critical', 'Critical'), ('unknown', 'Not Evaluated')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=25)),
                ('technician_name', models.CharField(blank=True, max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
