# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreport',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='laboratory.labtest'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['status'], name='laboratory__status_245ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['patient'], name='laboratory__patient_1e1eb8_idx'),
        ),
    ]
