# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(max_length=20, unique=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('symptoms', models.TextField(blank=True)),
                ('consultation_notes', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('prescription_notes', models.TextField(blank=True, help_text='Free-text prescription recorded during the consultation.')),
                ('advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('referred', 'Referred'), ('follow_up_required', 'Follow-up Required'), ('cancelled', 'Cancelled')], default='waiting', max_length=30)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_visit', to='appointments.appointment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_visits', to='hospital.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'OPD visit',
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
    ]
