# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('lab_values', models.JSONField(blank=True, default=list)),
                ('important_dates', models.JSONField(blank=True, default=list)),
                ('organisations', models.JSONField(blank=True, default=list)),
                ('classification', models.CharField(blank=True, max_length=60)),
                ('provider', models.CharField(default='demo', max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI summary',
                'verbose_name_plural': 'AI summaries',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('source_label', models.CharField(blank=True, max_length=200)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('language', models.CharField(default='eng', max_length=20)),
                ('engine', models.CharField(default='tesseract', max_length=40)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('page_count', models.PositiveSmallIntegerField(default=1)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('preprocessing_notes', models.CharField(blank=True, max_length=250)),
                ('processed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('medical_certificate', 'Medical Certificate'), ('referral_letter', 'Referral Letter'), ('imaging_report', 'Imaging Report'), ('insurance_document', 'Insurance Document'), ('consultation_note', 'Consultation Note'), ('consent_form', 'Consent Form'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes.')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('checksum', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the file contents, used for duplicate detection.', max_length=64)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='uploaded', max_length=20)),
                ('ocr_error', models.CharField(blank=True, max_length=250)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
