# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('arrival_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('triage_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('condition_notes', models.TextField(blank=True)),
                ('vitals_summary', models.CharField(blank=True, max_length=250)),
                ('treatment_given', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('triaged', 'Triaged'), ('in_treatment', 'In Treatment'), ('observation', 'Under Observation'), ('admitted', 'Admitted to Ward'), ('discharged', 'Discharged'), ('referred', 'Referred'), ('transferred', 'Transferred')], default='waiting', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Emergency visit',
                'ordering': ['-arrival_time'],
            },
        ),
    ]
