# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0003_initial'),
        ('emergency', '0001_initial'),
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvisit',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_visits', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='emergencyvisit',
            index=models.Index(fields=['priority', 'status'], name='emergency_e_priorit_ef6dc4_idx'),
        ),
    ]
