# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=20, unique=True)),
                ('scan_type', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('echo', 'Echocardiography'), ('mammography', 'Mammography'), ('pet', 'PET Scan')], max_length=20)),
                ('body_part', models.CharField(blank=True, max_length=80)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('radiologist_name', models.CharField(blank=True, max_length=120)),
                ('technician_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.CharField(blank=True, max_length=300)),
                ('report', models.TextField(blank=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_studies', to='patients.patient')),
            ],
            options={
                'ordering': ['-appointment_date', '-created_at'],
            },
        ),
    ]
