# Generated by Django 6.1.1 on 2026-09-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radiology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyreport',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='radiologyreport',
            index=models.Index(fields=['status', 'scan_type'], name='radiology_r_status_834932_idx'),
        ),
    ]
