# Generated by Django 6.1.1 on 2026-09-28 06:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=140)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(blank=True, max_length=80)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('route', models.CharField(blank=True, default='Oral', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('dispensed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('generic_name', models.CharField(blank=True, max_length=140)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('cardiovascular', 'Cardiovascular'), ('antidiabetic', 'Antidiabetic'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('neurological', 'Neurological'), ('vitamin', 'Vitamin / Supplement'), ('vaccine', 'Vaccine'), ('iv_fluid', 'IV Fluid'), ('topical', 'Topical'), ('other', 'Other')], default='other', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=140)),
                ('batch_number', models.CharField(blank=True, max_length=40)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=20)),
                ('unit', models.CharField(default='tablet', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage', models.CharField(blank=True, default='Room temperature', max_length=80)),
                ('prescription_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('discontinued', 'Discontinued')], default='available', max_length=20)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory.supplier')),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='admissions.admission')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
